### ISSUE TITLE
mkdir bug with busybox

### ISSUE THREAD

**Issue by buzzy** [tytso/e2fsprogs#112]
There is a bug in the install-sh script.

When running "configure", the scripts checks if a thread-safe "mkdir -p" exists on the system. It apparently checks this by running "mkdir --version" and checks for some valid strings. The "wget" that comes with busybox is not included in that list of strings, so the configure scripts uses "install-sh -c -d" as a fallback. However, that scripts does not support something like:

install-sh -c -d /one/dir/here /another/one/here

Which is used when running "make install", thus installing the package fails.

So either the install-sh script needs to be changed to support multiple directory paths in one go, or the Makefile needs to be changed to have seperate rows for each separate directory path that needs to be created.

**Comment by tytso** [comment]
Does using the latest version from libtool's install-sh work?   On a Debian system, it can be found at: /usr/share/libtool/build-aux/install-sh.   I haven't updated that file because most of the build systems which I support for e2fsprogs don't need install-sh, since they generally have a real install binary.  Install-sh is a fallback for those systems that don't have coreutils installed.

Install-sh (as well as all of the files from the config directory --- e.g. config.guess, config.sub, etc.) are not files that I support, but rather files that I copy from autoconf, and related packages.   If the install-sh file from autoconf/libtool's build-aux files don't work, please submit a bug to folks who maintain that program.

**Comment by buzzy** [comment]
I appreciate your response! Actually, I just ended up compiling and installing coreutils, so no big deal. Another way that also worked, was to set MKDIR_P="mkdir -p" as environment variable. I am working on a "linux from scratch" system so no pre-compiled package available. I haven't checked with any other install-sh than the one that came with your sources, so I am not sure if newer one works. I just though you might wanted to know that the way it stands now, your package pretty much requires coreutils because the install-sh bundled with the current source files is broken.

**Comment by libTorrentUser** [comment]
I'm in the **exactly** same boat as buzzy. I'm also working on a Linux From Scratch system and I can confirm that install.sh fails with busybox (the host machine is running Alpine Linux.)

Currently I went with setting `MKDIR_P="mkdir -p"`, and that works fine.

I can also confirm that the install.sh that comes with libtool-2.4.7 seems to be working fine. I didn't try building e2fsprogs with it, but I manually tested `install-sh -c -d dir1 dir2 dir3` and it worked perfectly. The install.sh that comes bundled with e2fsprogs just creates the first dir.
