### ISSUE TITLE
e2fsprogs-1.44.4: mke2fs -n overwrites filesystem

### ISSUE THREAD

**Issue by BusinessKid** [tytso/e2fsprogs#17]
I've recently overwritten an ext4 filesystem by following a procedure in the e2fsck man page. Under the '-b' option,  it recommends running 'mke2fs -n' to find the locations of the various superblocks. mke2fs -n actually overwrote the disk. Some useful links

The LQ [thread:](https://www.linuxquestions.org/questions/slackware-14/bug-in-mke2fs-or-e2fsck-man-page-4175648558/)

Next, the offending package: [https://drive.google.com/open?id=1zUtXwHQ4ttfq5-8-zXSrHcpM7kpVvWvu](url)
I'm using the e2fsprogs Slackware64 package. ; Tar -xf in a directory recreates the files.  Something isn't right with one of the links above, but I'm sure You'll manage. If you look at the thread, further comment is superfluous.

**Comment by tytso** [comment]
Can you give me a reliable repro where it actually erases the file system?   As in, please give the exact sequence of commands and how you verified that the file system was actually erased?

**Comment by BusinessKid** [comment]
Yes. Someone was in difficulty on LQ about a 142G partition, I was advising on the 'e2fsck -b' option, so I ran mke2fs -n on my 135G partition to get the superblock locations.
# mke2fs -n /dev/sda1
mke2fs 1.44.5 (15-Dec-2018)
/dev/sda7 contains a ext4 file system
        last mounted on / on Tue Feb 19 13:12:26 2019
Proceed anyway? (y,N) y
It then rewrote the (unmounted) filesystem without further questioning. sda7 had my VMs and some data directories, and I had a recent backup, so when they were erased it was an inconvenience, not a disaster. Not everyone will feel that way!!
The LQ thread linked above also had a link to my exact slackware64 package. All the information you want is in that thread.

**Comment by tytso** [comment]
That's anecdata.  I'm asking for a **reliable**, **reproducible** test case that I run use myself.   For example:

<tytso@cwcc> {/build/e2fsprogs-maint/misc}  
997% rm -f /tmp/foo.img
<tytso@cwcc> {/build/e2fsprogs-maint/misc}  
998% mke2fs -t ext4 -q /tmp/foo.img 4M
<tytso@cwcc> {/build/e2fsprogs-maint/misc}  
999% debugfs -w -R "write /etc/motd motd" /tmp/foo.img
debugfs 1.44.5 (15-Dec-2018)
Allocated inode: 12
<tytso@cwcc> {/build/e2fsprogs-maint/misc}  
1000% mke2fs -n /tmp/foo.img
mke2fs 1.44.5 (15-Dec-2018)
/tmp/foo.img contains a ext4 file system
	created on Wed Feb 20 12:19:55 2019
Proceed anyway? (y,N) y
Creating filesystem with 4096 1k blocks and 1024 inodes

<tytso@cwcc> {/build/e2fsprogs-maint/misc}  
1001% debugfs -R "stat motd" /tmp/foo.img
debugfs 1.44.5 (15-Dec-2018)
Inode: 12   Type: regular    Mode:  0644   Flags: 0x80000
Generation: 0    Version: 0x00000000
User:     0   Group:     0   Size: 286
File ACL: 0
Links: 1   Blockcount: 2
Fragment:  Address: 0    Number: 0    Size: 0
ctime: 0x5c6d8c42 -- Wed Feb 20 12:20:02 2019
atime: 0x5c6d8c42 -- Wed Feb 20 12:20:02 2019
mtime: 0x5c6d8c42 -- Wed Feb 20 12:20:02 2019
Inode checksum: 0x00004a8a
EXTENTS:
(0):1202
<tytso@cwcc> {/build/e2fsprogs-maint/misc}  
1002% exit

Script done on 2019-02-20 12:21:05-05:00 [COMMAND_EXIT_CODE="0"]

In this case, we can see the file system was not erased, since the file that was created is still there.    Can you give me a series of commands which replicates what you've reported using the slackware e2fsprogs?

**Comment by BusinessKid** [comment]
In the LQ thread, I linked the exact package for download. I'm happy for you if you can't reproduce it. I erased a 135G real partition with the command mkie2fs -n /dev/sda7. That's not anecdata, that's fact.
The reality that you're there and I'm here hardly changes it. Furthermore, the drive changed from ext4 to ext2.
In your honour, I tried replication it with a drive image, and the same binary of mke2fs.  I made a 10G image, rsync'ed it with my Mint-19.0 / drive (6.6G), and ran mke2fs on it. It wasn't erased. But my **real partition was erased** and reclassified as ext2. Go figure. I suggest you try it on a real partition.
It makes little difference to me. I'll know better than to try that (mke2fs -n)again, regardless of what your man pages say.

**Comment by tytso** [comment]
The problem is if we can't reproduce it, the bug report is not actionable.   And from my perspective, **you** may be sure that that's what you did, but **I'm** not.   I've tried it on a real partition, and I still can't reproduce it.

If you can give me a reproducible test case, I'm happy to take a closer look.   But otherwise, there's literally noting I can do, except wonder if you're mistaken.
