### ISSUE TITLE
Whether it is possible to erase the signature of the old file system before executing mkfs.ext4

### ISSUE THREAD

**Issue by biubiuzy** [tytso/e2fsprogs#180]
When users recreate the file system, they may forget to erase the old file system, resulting in file system probe errors and mount failed.
see https://github.com/util-linux/util-linux/issues/2701

**Comment by tytso** [comment]
mkfs.ext4 will wipe at least the first few hundred kilobytes (in the case of a 4 MiB file system, 392k; in the case of a 1 TiB file system, the first 6 MiB) and the last 32k of the file system, which historically has been *plenty* to erase signatures of old systems.   It appears that the drbd signature is in the first 4k, so I don't see why it wouldn't be wiped.

I've looked at the documentation of drbd, and it's ***terrible***.  I can't figure out how to format a drbd device after about 10 minutes of puzzling the through the user guide before I gave up as not worth my time.   If you want to give me a precise reproduction instruction that makes it obvious how to create a drbd device, please feel free to reopen this bug.  Otherwise, I'm going to close it as "not reproducible".
