### ISSUE TITLE
support for clearing ext4 "large_dir" feature

### ISSUE THREAD

**Issue by soredake** [tytso/e2fsprogs#28]

**Comment by tytso** [comment]
Feel free to submit a patch.  :-)

**Comment by indeed-a-genius** [comment]
Until then I'd like to suggest displaying a warning when setting this flag so users are aware that:
- it's irreversible
- will cause most Linux systems not to boot if used on the system partition (because grub doesn't support it)

**Comment by tytso** [comment]
large_dir is an ro_compat feature ---- which is to say, if an implementation sees a feature flag in the feature_ro_compat bitfield which it doesn't understand, and that implementation is only doing read-only operations on the file system, it's safe to ignore that unknown read-only feature bit.

I've looked at the grub sources, and grub ignores the feature_ro_compat field entirely, and only checks the feature_incompat bitfield --- which makes sense, because grub only needs to read file system data; it doesn't need to modify the file system data.

As such grub should not be discomfited by the the presence of the large_dir feature flag.

**Comment by indeed-a-genius** [comment]
Do you mean in its current state grub should work with large_dir? Or that grub needs to be patched in order to ignore large_dir?
The grub bug is confirmed [in]( https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1844012) [several](https://savannah.gnu.org/bugs/?56897) [places](https://wiki.archlinux.org/title/GRUB#error:_unknown_filesystem).

**Comment by tytso** [comment]
The first two links that you've cited refer to a completely different feature, metadata_csum_seed, which is a feature in the feature_incompat bitfield, which is very different from the feature_ro_compat bitfield.   The third link, which is to the Arch wiki, does mention large_dir feature, but that is not substantiated by code inspection of grub.   I'm currently on travel so I'm not set up to do the test, but from looking at the source code, I can't see how Grub would be influenced by the presence of *any* bit in feature_ro_compat, including EXT4_FEATURE_INCOMPAT_LARGEDIR.   

Let me turn your question around.  I have you personally experienced grub refusing to read a file system with the large_dir feature?

**Comment by indeed-a-genius** [comment]
I appreciate you looking into this, hopefully someone gets it fixed in grub. And yeah, I'm currently stuck with an unbootable system, so wanted to help others avoid that.

**Comment by tytso** [comment]
There's a patch to grub here[1] which should fix things.   If you have the ability to rebuild grub and verify that this fixes things, that would be great.

[1] https://savannah.gnu.org/bugs/index.php?61606

**Comment by tytso** [comment]
So *if* you just set large_dir, and you haven't created any really large directories, what you can do is run this command from a rescue CD (while the file system is not mounted):

debugfs -w -R "feature ^large_dir" /dev/sdXX

Then force a full fsck just to be sure:

e2fsck -f /dev/sdXX

This is *not* going to do good things if there are large directories, since by definition large directories are too big to be supported otherwise, and it leaves open the question of what we should do with that directory?   I suppose we could clear the htree bit, and make it be a linearly searched directory, but if it's that large, it's going to be painful to use.   This is one of the reasons why we can't make removing large_dir to be easily supported.   There are traps and land mines involved.

On the other hand, for users who like randomly turning on file system features just to see what they do (which to be honest, has its own risks) this is something that can be done using debugfs --- although anything using debugfs should be done by people who know what they are doing.   (The original reason why I created debugfs was so I could corrupt file systems to test e2fsck....)

**Comment by indeed-a-genius** [comment]
THANK YOU!! 
I deleted the large directory (it wasn't crucial), then removed the flag, ran e2fsck which gave me a few "extent tree could be narrower" warnings to which I answered optmize.
After a reboot the system works!
