### ISSUE TITLE
Fails to build with gettext 0.20

### ISSUE THREAD

**Issue by rossburton** [tytso/e2fsprogs#34]
With gettext 0.20:

```
ERROR: Use of AM_GNU_GETTEXT without [external] argument is no longer supported.
```

The fix is a trivial change to `configure.ac`:

```
-AM_GNU_GETTEXT
+AM_GNU_GETTEXT([external])
```

**Comment by tytso** [comment]
What operating system are you using, and what is your configure options are you using?

There is a AM_GNU_GETTEXT defined in aclocal.m4 which is what is used in the distributed configure script.   I'm guessing you're messing with the aclocal.m4?

**Comment by rossburton** [comment]
Linux.  We're rebuilding the autotools from scratch using autoreconf because we patch configure.ac so need to.

**Comment by tytso** [comment]
Why not just use "autoconf", and not autoreconf?

I should probably update the included gettext in the intl directory, but that needs to happen before I can update the relevant macros in aclocal.m4, and that hasn't been a super-high priority for me since no one else has been complaining and glibc has full glibc support, which means the intl directory is only needed for FreeBSD, Illumos/Open Solaris, et. al.

**Comment by rossburton** [comment]
Continuing this, you now also need to say what version of gettext is needed.

`AM_GNU_GETTEXT_VERSION([0.19.1])` works, although there are better approaches.

**Comment by tytso** [comment]
I've updated e2fsprogs 1.46.0 to use a newer version of gettext (0.19.8).   This should solve the problem for you, since autoreconf should now work.  Note that it is *not* safe to use autopoint, as I had to make manual changes to the po/Makefile.in.in file in order to make it properly integrate into e2fsprogs's build system, and autopoint will blindly nuke the po/Makefile.in.in file and then Things Will Not Work.
