### ISSUE TITLE
[resize2fs] expanding empty ext4 fs to 2TB always leads to corrupt filesystem

### ISSUE THREAD

**Issue by acostach** [tytso/e2fsprogs#50]
Hi,

Having a problem with resize2fs, not sure if it's a bug or a limitation, or something else. When trying to expand an **empty** 200MB ext4 filesystem that has a 1K block size, to the end of the 2TB disk, resize2fs appears to corrupt it.

Running fsck afterwards shows these errors:
```

fsck -f /dev/sdb6
fsck from util-linux 2.31.1
e2fsck 1.44.1 (24-Mar-2018)
ext2fs_check_desc: Corrupt group descriptor: bad block for block bitmap
fsck.ext4: Group descriptors look bad... trying backup blocks...
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Block bitmap differences:  +(212993--219700) +(229377--236084) -417793 -417803 -417825 -417829 -417835 -417857 -417862 -417867 -(417889--417893) -(417895--417898) -(417900--417901) -417903 -417918 -417937 -418033 -(418036--418037) -418039 -418041 -(418044--418046) -418050 -418059 -418082 -418085 -418091 -418113 -418118 -(418122--418123) -(418145--418154) -(418156--418159) -418174 -(418193--418194) -(418289--418293) -418295 -418299 -418301 -418303 -(418305--418306) -418315 -(418337--418338) -418341 -418347 -418369 -418374 -418380 -418416 -418430 -(418449--418450) -418545 -418547 -(418549--418551) -(418553--418556) ... 107511290 -107511294 -107511296 -107511298 -(107511319--107511321) -107511330 -107511333 -(107511351--107511353) -107511366 -107511371 -(107511383--107511385) -107511408 -107511422 -(107511441--107511442) -107511541 -107511546 -107511550 -(107511552--107511554) -(107511575--107511577) -(107511585--107511586) -107511589 -(107511607--107511609) -107511622 -(107511626--107511627) -(107511639--107511641) -107511664 -107511678 -(107511697--107511698) -(107511793--107511794) -107511798 -107511802 -107511806 -107511808
Fix<y>? yes


myfs: ***** FILE SYSTEM WAS MODIFIED *****
myfs: 3454/244101120 files (0.5% non-contiguous), 31440202/1952801792 blocks
```

Tried with two different 2TB HDDs and is reproducible every time, with v1.45.6 too, when expanding to 1024GiB or greater.

If doing a resize to only 1023GiB, the problem doesn't seem to appear.  With 2K or 4K block sizes the issue is also not visible.

**dumpe2fs output:**
- before expand: https://gist.github.com/acostach/af08dddb56e73b0600559a19d0daeeb0

- after expand: https://gist.github.com/acostach/c622954e17b7676c240eb4c6b6cef387

Any idea what could cause this?

Thank you!

**Comment by tytso** [comment]
The problem is that when you create a file system which is tiny (e.g., 200MiB), we use a blocksize of 1k.   With a block size of 1k, the backup superblock is located at block 8193 (e.g., the first block of the second block group in the file system).   But when using a block size of 1k, the number of block group descriptors is so large that it completely fills the first block group, and spills into the second block group:

Group 0: (Blocks 1-8192) csum 0x0e73
  Primary superblock at 1, Group descriptors at 2-8193

and so when the backup superblock is written it trashes the block group descriptors:

Group 1: (Blocks 8193-16384) csum 0x98cc [INODE_UNINIT]
  Backup superblock at 8193, Group descriptors at 8194-16385

So the bug is that resize2fs should have refused to resize the file system past 1023 GiB. 

The next question is why in the world are you trying to do this?     In general, people who try to take a super-small file system and then inflate them to really big file systems, are just asking for problems --- performance problems, if nothing else.   There are.... misinformed people who will try to install a Linux distribution onto a 1 TB disk, and then shrink it down to a super-small file system that might be, say, a GB, just so that it can be installed via an image copy onto a 14TB disk, and then resized up to 14TB.   But that's going to result in the file system image being massively fragmented, and performance will be rotten.

There are also people who will start with a cloud elastic block device which is 10GB, wait until it gets 99% full, and then resize it to 11GB, and then when it gets up to 99%, resize it up to 12GB, and repeat.   This will also lead to massive file system fragmentation.   I understand why a cheapskate might want to do this, but this will lead to tears.

The original design point of resizing was to allow a file system to say, double in size when a RAID array was grown.   10x or even 100x growth will also work, although by the time you get to 1000x you're really started to push things.   But starting at 100MB, ignoring the blocksize limitations (1k block file system are super non-performant; they are fine for floppy disks and cheap USB thumb drives, where space efficiency is more important than performance, where you are bottlenecked by the speed of the device anyway).    When you start doing extreme things outside of the original design envelope, you should be surprised when you encounter problems.    (Which is great in terms of generating bug reports, for which I'm grateful --- but I'm still wondering why h*ck are you doing something so... outré.)

**Comment by acostach** [comment]
Hi @tytso , thank you so much for taking time to reply!

The use-case on which we encountered this is:

- An embedded device uses an sd-card/usb-key to boot a 'flasher' image.

- This flasher image writes another pre-built image to the device's main storage using dd. The flashed image a two A/B root partitions and one small data partition which will be enlarged during the first boot, as device storage capacity varies from one device to another and it's not known beforehand.

- The data partition is empty in this particular case, but that's just in this case. Files may be pre-loaded on it, case in which it gets enlarged a bit, just enough for those files to fit in. More user files get stored in this data partition during normal device operation.

- Now, in general these embedded systems have grown to 8G-32G main storages, some going up to 256GB.  However, in this particular case, the device flashed by the user has a 2T nvme..

**Comment by tytso** [comment]
I'd strongly suggest that you use "mke2fs -t ext4 -T default -b 4k" so that the file system uses a 4k block size and a 256 byte inode, which will accelerate extended attributes (which will be a big deal especially if you are using SELinux, for example).

That's because mke2fs tries to tune the file system automatically for a particular size file system, and creating a eeny-weeny file system and then growing it is going defeat these automatic heuristics.   See the man page for mke2fs.conf, and the default mke2fs.conf installed on your system.

**Comment by acostach** [comment]
Yes, we'll switch to 4k block size as you recommend, thank you very much again for your thorough explanation!
