### ISSUE TITLE
Is this the new canonical e2fsprogs development location?

### ISSUE THREAD

**Issue by ryandesign** [tytso/e2fsprogs#64]
Is this the new canonical e2fsprogs development location?

The README still says the official URL is http://e2fsprogs.sourceforge.net and that bugs should be reported by email. Should they be reported here to GitHub instead? Reporting bugs on a public web site is more desirable than using private email.

The web page https://sourceforge.net/projects/e2fsprogs/support says:

> Ext2 Filesystems Utilities says the best way to get help with its software is by visiting http://sourceforge.net/tracker/?func=add&group_id=2406&atid=202406.

However visiting that URL goes to the Support section of the e2fsprogs SourceForge issue tracker which is overrun with spam and in which the Create Ticket functionality has been turned off.

There is no mention of this GitHub repository on the SourceForge project page or web site. If it is official, it should be mentioned there.

**Comment by tytso** [comment]
Github is not any more canonical than sourceforge.   The primary e-mail list where ext4 development takes place (and this includes the userspace utilities) is the linux-ext4 mailing list on vger.kernel.org.   Initial triage for user bug reports should go to their distribution's bug reporting system, since most users get e2fsprogs from their Linux distro --- and there are so many e2fsprogs users that it's not scalable to have ext4 developers explain to users how they are making various basic system administration mistakes.   Basically, the number of users vastly outnumbers the time available to ext4 developers.

I do pay attention to a number of different bug trackers, so long as they bug requests are useful.   For example, SourceForge's bug tracker became overrun by spam, so I turned off ticket creation on it almost ten years ago.   Fortunately, most bug reports on Debian's are useful and thoughtfully crafted, with enough information that most of the time, it's worthwhile to respond to them.  The Ubuntu bug tracker has far too many less-than-useful bug reports, and so I stopped pay attention a long time ago; my time is too valuable to waste time supporting Ubuntu users for free.  Since Canonical charges $$$ from their real customers, and they don't bother triaging or grooming their community bug tracker, I've stopped paying attention to it.  Canonical personnel know how to contact the linux-ext4 mailing list, and if they only bother to handle paid bug reports, that's up to them.    When it comes closer to a release, I do take a quick scan through github's issue tracker to see if there is anything that would be useful to handle.   But I rarely handle pull requests, because Github's patch review is system is far inferrior, from the maintainer's perspective, than using simple e-mail.   Just as kernel patches need to go through discussion and review on the linux-kernel, I make no guarantees about taking a look at Pull Requests sent via github.    (Some of the Pull requests which I resolved had languished for months.) 

I do have to say, the more recent pull requests sent to github were much more reasonable --- in the past, the pull requests for e2fsprogs were 99% pure, unadulterated garbage, since github actively makes it hard for users to follow the kernel submission guidelines documented at:

https://www.kernel.org/doc/html/latest/process/submitting-patches.html

(Which is why I had stopped regularly checking github's pull requests for e2fsprogs.....   But I do sometimes will check to see if there's any intelligent life hiding in the pull requests; it just might take a while.  :-)

**Comment by ryandesign** [comment]
Thanks for the response but I think some things need to be changed from your end to improve the situation, rather than just close this ticket.

Let me try to explain. I am the maintainer of e2fsprogs in MacPorts (a package management system for macOS). What started my quest to report bugs to you now was that I became aware that a new version of e2fsprogs was released and I wanted to update the MacPorts port to that version. There are bugs in the e2fsprogs build system that I have been working around in our port for years. In doing the update, I checked whether the workarounds for the build problems were still needed, and I found that they are, so I wanted to file a bug report so that they can be fixed properly.

When the e2fsprogs port was added to MacPorts in 2008, its homepage was listed as http://e2fsprogs.sourceforge.net. When I want to report a bug, I start by visiting a project's homepage and looking for a bug reporting link. **There isn't a bug reporting link on the homepage; one should be added.**

From the URL I surmise that the project is hosted at SourceForge so I visit https://sourceforge.net/projects/e2fsprogs/ and look at [Tickets: Bugs](https://sourceforge.net/p/e2fsprogs/bugs/) but the Create Ticket button is disabled. I find the [Support tab](https://sourceforge.net/projects/e2fsprogs/support) and when I looked at it yesterday, it said the best way to get help was to visit [Tickets: Support Requests](https://sourceforge.net/p/e2fsprogs/support-requests/) but again the Create Ticket button is disabled and the support requests shown there are mostly spam from 9 years ago. The fact that this spam has not been removed by the owner of the project and that the recommended way to get support was still referring me there despite the create function being disabled gives the impression that the project is abandoned. I suspect many users would throw up their hands in despair at this point and discontinue attempting to report problems to you, which is a detriment to the project. If people can't report bugs to you, you can't fix them. **The spam should be removed from the SourceForge trackers.**

The project homepage at SourceForge also gives no indication that the project is alive. If I hadn't known prior to visiting the page that a new release had just happened, I would have had no way of knowing it by looking at it. The page erroneously states that it was last modified in 2010 (when in fact it was modified last week for the new release) and the design of the page gives no evidence to the contrary. (I'm not complaining about the late 90s design of the page, just saying that it contributes to the impression that the project may be abandoned.) What might help is if you would **update the last modified date on the homepage** when you update the page, or **put the date of the last release somewhere near its version number**.

Today I see that the [Support tab](https://sourceforge.net/projects/e2fsprogs/support) has been changed to say "Unfortunately, this project hasn't indicated the best way to get help. Check out the other support options below." The "support options below" mostly don't work either. The first link is to mailing list archives, one of which has had only two messages, both 21 years ago, and the other of which has no messages. **Maybe the whole mailing lists section could be removed.** The next four links are to the spammy disabled SourceForge trackers. Only the last link, to the [Discussion](https://sourceforge.net/p/e2fsprogs/discussion/) groups appears to be current. **The SourceForge Support tab should be changed to a URL where you will respond to bug reports** such as perhaps this GitHub repository's Issues tab. **Ancient unhelpful links should be removed** from the SourceForge Support tab.

I'm not alone in finding it hard to figure out how to report bugs; the question has come up in the Discussions before ([here in 2014](https://sourceforge.net/p/e2fsprogs/discussion/7052/thread/12981cf6/), [here in 2017](https://sourceforge.net/p/e2fsprogs/discussion/7053/thread/2caf9bc1/)). Referring users to report bugs in their Linux distribution is not satisfactory for those users who are not using Linux, and is not helpful for those who are maintaining the packages in their distributions and have encountered problems that need to be reported to the developer. Users want to report issues in a web-based issue tracker. Most developers I know prefer to receive bug reports that way as well. It provides a structured way to track issues. Each issue gets assigned a number. Discussion about that issue and its eventual fix is gathered together onto a single page which has a single URL that can be passed around easily. In many issue trackers like GitHub's, commits and related issues can be cross-referenced automatically. Perhaps you prefer to receive bug reports via email, but it would be difficult to understand why. It is more difficult for everyone to use, does not provide others with a way to see what bugs have already been reported, and is an additional barrier discouraging users from reporting problems, which you should instead be encouraging.

Having multiple ways to receive bug reports -- SourceForge trackers, SourceForge discussions, GitHub issues, personal email, mailing list -- would seem to make it more likely that duplicates would be submitted. Users would have a harder time finding prior bug reports, since a user is unlikely to search all of the different systems. I would think you would want to streamline so that you **have only one central method of reporting and viewing bug reports**, whatever that might be, to save both you and your users time.

The SourceForge web page and project page make no mention of this GitHub repository. I only found it by Googling, and the lack of cross referencing made me unsure whether it was a real upstream project location or just something someone had imported (hence me filing this issue). The only hint that it might be a valid upstream repo was your username in the URL, but I shouldn't have to guess. **I recommend mentioning this GitHub repo on the SourceForge web page and project pages** to reassure people that it is in fact associated with the project.

**Comment by tytso** [comment]
Speaking from a purely selfish point of view, what scales the best for me is when the distribution maintainers (e.g., for Red Hat, SuSE, FreeBSD, etc.) contact me directly, or preferably, by sending patches to the linux-ext4 kernel mailing list at vger.kernel.org.   I'd prefer for you (ryandesign) to send me patches or bug reports.   I would much rather not want all of *your* users to send me bug reports, just as I prefer that the FreeBSD users send their bug reports to Matthias Andree, since I don't know FreeBSD all that well; I don't develop on FreeBSD, and I simply can't deal with gazillions of end-users contact me (or some bug tracker where there isn't someone actively grooming the bug reporting system for me).   It just doesn't scale.

I won't call it deliberate that it's hard to find the bug reporting front-end, but I want the Ubuntu users to be reporting bugs to Ubuntu; the Red Hat users to report them to Red Hat; the FreeBSD users to report them to FreeBSD; and so on.   It's the only way it's going to scale.  I don't have the *time* to answer every single user's "why did I lose my files" (and 99.999% of the time it's user error, it's not a useful e2fsprogs bug report, and so I need other people to act as a filter so I only get well formed bug reports).   If users want something better than that --- well, I'd like to have a private jet.    :-)

As far as "bugs in the e2fsprogs build system", I happen to know that one of the ext4 developers does build e2fsprogs on MacOS, and he sends me patches to fix the problems he runs into.   Ultimately, that's going to be the best way to "report bugs in the build system".   I don't have a MacOS system, not being interested in paying $$$ to Apple, and so sending me bug reports in the form of a patch is the most useful.   And since most of the ext4 maiintainers follow the linux-ext4 mailing list on kernel.org, sending the message to the mailing list really is the best place to send the patches.

I know that end users might want a web front end, but hopefully developers are willing to deal with the old-fashioned e-mail approach.

**Comment by tytso** [comment]
By the way, if *you* want to create lots of FAQ's and documentation, and help to groom the SourceForge bug tracker, we can talk.   The main thing that frustrates me is this attitude of entitlement where people expect me and the very small team of ext4 developers to provide free support, huge amounts of documentation, for the literally millions of Linux users out there.   If you want curated web-based bug trackers, you can pay $$$ for a supper entitlement to Red Hat or Canonical.   These sorts of things don't come for free, and without a huge amount of effort from volunteers other than the core developers, it's Just Not Happening.

Rather than providing free support to end users who don't pay me a dime, I'd much rather support those developers who are also contributing to the project.   Or work on test regression systems for ext4 (see: https://thunk.org/gce-xfstests and https://github.com/tytso/xfstests-bld).   Or adding new features to further the business goals of my employer, who pays my salary (https://lwn.net/Articles/842385/).   Or helping developers who work for other companies for their business objectives, because they in turn help me and other members of the ext4 developer community out.   Open source is about developers helping other developers out, so we can jointly create great things.  Users are useful for providing bug reports, but the problem is they have to provide *useful* bug reports.   When the vast majority of the bug reports from certain sources are 99.99% worthless, and when there are literally millions of users, there isn't enough time in the day to provide free customer support by grooming bug trackers and answering "you forgot to plug it in" kind of questions.   That's why we have paid support options in the Linux ecosystem.   

To date, it's not been a problem for most serious developers to find me and the rest of the ext4 development community.  File system development is a non-trivial amount of effort; very little gets done via drive-by patches/pull-requests.   As a result new developers usually need to be working close to full-time on file system development work, and they effectively go through an apprenticeship period; which might be via an internship program, or when a full-time engineer works at a company, and is mentored by other more senior engineers at that company.  (We have had new features explicitly added to benefit Android and ChromeOS, as well as the Lustre cluster file system; in fact multiple Lustre developers are regularly submitting patches, and are on the weekly ext4 video conference meeting, along with other engineers from SuSE, IBM, Oracle, and Google.   And it's not all corporate engineers; we also have a hobbyist who used to do file system performance work for HP before he took early retirement, and is now contributing significant ext4 patches and root causes file system regressions caused by changes in other parts of the kernel.)

I recognize that people who are porting e2fsprogs to other OS's may be an exception to this rule; all I can say is that Matthais from the FreeBSD Ports community had no trouble finding me, and my e-mail is in the sources.
