### ISSUE TITLE
[RFE] Switch to fuse3

### ISSUE THREAD

**Issue by ovitters** [tytso/e2fsprogs#66]
Hi,

Would it be possible to have e2fsprogs make use of fuse3 instead of fuse (version 2)? Fuse maintainers/developers seem to encourage usage of fuse3 instead of fuse2. I tried to search if this was asked before, seems that in end 2018 it was discussed, see https://lists.debian.org/debian-devel/2018/12/msg00296.html. Various functions have been renamed in fuse3, see https://github.com/libfuse/libfuse/releases/tag/fuse-3.0.0. So although they can both be installed at the same time, a fuse-using application won't be able to compile as-is against fuse3.

The debian-devel mail mentions that e2fsprogs should ideally still compile against old-old-stable. I'm not sure yet if that would be possible if e2fsprogs switches to fuse3. This as I'm not sure old-old-stable Debian has fuse3.

Thanks

**Comment by tytso** [comment]
old-stable currently does not have fuse3.   This will change when Bullseye because Debian Stable, and Buster becomes old-stable.   But old-old-stable will still not have fuse3.

It's unclear to me what the benefits are for fuse3, and I personally don't have the time to do the work to port fuse2fs to use fuse3. Looking at the changelog, it's not trivial set of changes.

**Comment by DrDaveD** [comment]
One big advantage to fuse3 is that it supports the ability of pre-opening/pre-mounting /dev/fuse and passing that file descriptor in place of the mount point.  This was added 5 years ago in libfuse/libfuse#291.   This enables a privileged program to open /dev/fuse ahead of time and then invoke the application that uses fuse completely unprivileged.

I would like to be able to use this from the [Apptainer](https://apptainer.org) privileged mode in order to support mounting user-owned ext3 filesystems without using the kernel filesystem driver, which as @tytso knows is a serious security risk.

**Comment by DrDaveD** [comment]
I made a pull request for this in #172
