### ISSUE TITLE
badblocks stuck forever

### ISSUE THREAD

**Issue by dwebfan** [tytso/e2fsprogs#69]
One of my disk shows input/output error when I access certain directories, then I want to use `badblocks` to find out the location of bad blocks, but seems like it is stuck forever after a while, and no timeout  option. Can you please suggest me a way to proceed? Thanks

**Comment by BrendonIrwan** [comment]
For a timeout, use other programs, but I don't have an example.

Use the `-v` option if you want to see things.

Anyways, `badblocks` is not to blame.

I had the same problem but with an external disk. When things got "stuck," the disk sat idle. Safe removal didn't work. Manual removal caused `badblocks` to print false positives because the disk was no longer attached, and that is to be expected.

**Comment by tytso** [comment]
Not a badblocks bug.   You might try using the smartctl command, which is part of smartmontools.  But in general, with modern disks, when it gets to that point, you should just replace the HDD.
