### ISSUE TITLE
Test: Embedded linux image with e2fsck and return a 2.

### ISSUE THREAD

**Issue by linuxanonimous84** [tytso/e2fsprogs#70]
Hello,

I don't know if this the right place to put this question, sorry if it is not. I'm looking your regression tests in order to understand how they are performed because i need to create my own embedded linux image. This image when it boots has to perform e2fsck and it has to return a 2. So it means that it should require a boot after this value.

Checking your regression tests, all of them are img file so it means that they are already an image, so i cannot not use it directly. Is there any way that i can corrupt my image in order to be able to get a 2 from e2fsck?

Thanks for your time,

**Comment by tytso** [comment]
This isn't a great place for asking questions because I don't really monitor the github issues page.

E2fsck will return 2 if a file system was changed to address file system corruption, and the (root) file system was mounted read-only.  That's because the some of the incorrect file system data might have been cached in memory, and if the file system remounted read/write the incorrect the invalid data might be rewritten back to the file system, undoing the work of e2fsck.

Some distributions are now using an initramfs, and checking the root file system before it is mounted.   In that case, e2fsck will never return an exit status of 2.
