### ISSUE TITLE
resize2fs: New size results in too many block group descriptors

### ISSUE THREAD

**Issue by wenerme** [tytso/e2fsprogs#74]
can to grow ext4 fs.

```bash
sudo resize2fs  /dev/nbd0p2
resize2fs 1.46.2 (28-Feb-2021)
resize2fs: New size results in too many block group descriptors.
```

e2fsck report clean

```bash
sudo e2fsck /dev/nbd0p2
e2fsck 1.46.2 (28-Feb-2021)
/dev/nbd0p2: clean, 230243/249832576 files, 965174768/1048472576 blocks

sudo e2fsck -fy /dev/nbd0p2
e2fsck 1.46.2 (28-Feb-2021)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/nbd0p2: 230243/249832576 files (0.5% non-contiguous), 965174768/1048472576 blocks
```

fdisk report 1T partition, tried use rest space, still the same.

```bash
$ sudo fdisk -l /dev/nbd0
Disk /dev/nbd0: 1.5 TiB, 1649267441664 bytes, 3221225472 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x3c283df9

Device      Boot  Start        End    Sectors  Size Id Type
/dev/nbd0p1 *      2048     206847     204800  100M 83 Linux
/dev/nbd0p2      206848 2147690495 2147483648    1T 83 Linux
```

## more details

```bash
$ sudo tune2fs -l /dev/nbd0p2
tune2fs 1.46.2 (28-Feb-2021)
Filesystem volume name:   <none>
Last mounted on:          /
Filesystem UUID:          <>
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr dir_index filetype meta_bg extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize metadata_csum
Filesystem flags:         signed_directory_hash
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              249832576
Block count:              1048472576
Reserved block count:     32658598
Free blocks:              83297808
Free inodes:              249602333
First block:              1
Block size:               1024
Fragment size:            1024
Group descriptor size:    64
Blocks per group:         8192
Fragments per group:      8192
Inodes per group:         1952
Inode blocks per group:   244
First meta block group:   257
Flex block group size:    16
Filesystem created:       Sun Oct 20 21:58:50 2019
Last mount time:          Fri Feb 19 17:00:04 2021
Last write time:          Sat Jul 17 20:17:31 2021
Mount count:              0
Maximum mount count:      -1
Last checked:             Sat Jul 17 20:08:41 2021
Check interval:           0 (<none>)
Lifetime writes:          6813 MB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:               128
Journal inode:            8
Default directory hash:   half_md4
Directory Hash Seed:      <>
Journal backup:           inode blocks
Checksum type:            crc32c
Checksum:                 0x198449a0
```

**Comment by tytso** [comment]
The problem is that the file system was created using a 1k block size.   A file system with a 1k block size should only be used on very tiny file systems, where storage efficiency on a (for example) 2 megabyte USB thumb drive is much more important than the performance limitations and limitations in how big a file system can be grown.   Which is OK, because if you have a itsy-weeny thumb drive, you're generally not going to be resizing that file system to 2T.

There seems to be an anti-pattern by various embedded developers who think it's a handy-dandy idea to create a tiny file system, and expect to be able to resize it to very large sizes.   That doesn't work well.   And past a certain point, it doesn't work at all.  The bug is not in resize2fs.  It is in how you are trying to use it.....

**Comment by wenerme** [comment]
@tytso thanks, the image is create by script with default flags

so I guess the problem is this line `Block size:               1024` ?

and should always pass flag to mkfs.ext4 like `mkfs.ext4 -b 4096` ?

Why not make mkfs.ext4 default to 4k ?

**Comment by tytso** [comment]
mke2fs (aka mkfs.ext4) uses different defaults based on the size of the file system being created.   This is documented in the mke2fs man page.   See the descriptions for the -b and the -T options to mke2fs.   Also see the mke2fs.conf man page, and the default /etc/mke2fs.conf file, which includes the following:

[fs_types]
        ext3 = {
                features = has_journal
        }
        ext4 = {
                features = has_journal,extent,huge_file,flex_bg,metadata_csum,64bit,dir_nlink,extra_isize
                inode_size = 256
        }
        small = {
                blocksize = 1024
                inode_size = 128
                inode_ratio = 4096
        }
        floppy = {
                blocksize = 1024
                inode_size = 128
                inode_ratio = 8192
        }
        big = {
                inode_ratio = 32768
        }
        huge = {
                inode_ratio = 65536
        }

So for file systems which  are size "floppy" (less than 3MB) or "small" (between 3MB and 512MB) a blocksize of 1k gets used, because it's presumed that space efficiency is desired.  This is a hueristic, but defaults can always be overridden.   The anti-pattern is scripts that create tiny file systems and assume that inflating them to 1T or more is a sane thing to do.   It will cause problems, because file system parameters which are appropriate for a 2.88MB floppy might not be appropriate for a 2TB or 12TB hard drive.   If you find scripts which are doing this bad thing, please let them no that this is an anti-pattern, and not something that should be emulated or done in the future.
