### ISSUE TITLE
filefrag does not report correct values for btfs filesystem

### ISSUE THREAD

**Issue by axet** [tytso/e2fsprogs#84]
Hello!

filefrag does not report correct physical offsets for btrfs. All details with working example (btrfs_map_physical.c) is here:

https://bugzilla.kernel.org/show_bug.cgi?id=202803

e2fsprogs-1.46.4-1

**Comment by tytso** [comment]
This isn't an filefrag bug.  Filefrag uses the FIEMAP ioctl which is a kernel interface which is documented to return the physical block number.   Granted that the FIEMAP interface doesn't have support for multiple block devices, but that's something which the btrfs developers need to discuss on fs-devel mailing list to define an extension to the FIEMAP interface to support their use case.

The "working example" requires read access to the block device, which typically on root has (otherwise other users could read other users' private keys, health records, love letters, etc.) and filefrag is used by non-root users, and without know what kind of file system (or which block device) the user has passed to filefrag.  So when filefrag is run, e.g. "filefrag -v /home/tytso/testfile", filefrag doesn't know (a) which block device /home/tytso/testfile, (b) where the mountpoint for the file system is /home?  /home/tytso?, and (c) what kind of file system is being used to store /home/tytso/testfile.   That's because filefrag uses the documented FIEMAP interface.   

btrfs_map_physical.c is the moral equivalent of using the debugfs program for ext2, ext3, and ext4 file systems.   It requires read access to the block device, and it's not necessarily safe to use it on a mounted file system, since the file system metadata can be changing out from under the userspace program trying to descend through the b-tree which is the btrfs file system.    If you have root access, and if the file system is not mounted, then you can use debugfs to reliably find the physical mapping of a file on an ext4 file system --- and you might be able to use btrfs_map_physical on an unmounted btrfs file system to _safely_ find the mapping of a file on an unmounted file system.   But if the file system is mounted, and actively being modified, there is zero guarantees that debugfs and btrfs_map_physical will work correctly.   This doesn't stop file system developers from using these tools, of course.  But only when there is a human being who deeply understands what is going on, the risks that are involved, and how to handle failures.    The tool for a non-expert user who does not have root privs is filefrag, and the FIEMAP ioctl, and if btrfs doesn't properly support FIEMAP, then that's an issue you need to take up with the btrfs developers.

**Comment by axet** [comment]
Thanks, at least I do not have read all the code to get the same understanding.

I guess filefrag on btrfs case can be handled correctly and reported as unsupported.

'df -PTh file' can determine which filesystem file is located on without root access and can therefore be used to warn the user without destroying love letters if resume_offset set incorrectly... :imp:

**Comment by tasket** [comment]
FWIW, I think the correctness of the FIEMAP ioctl output depends on the use case.  The cases where its incorrect involve finding data blocks directly in the block devs underpinning the filesystem.

But for other cases (probably most) getting the Btrfs virtual block addresses seems fine:  It shows fragmentation patterns, and it shows consistently where extents reside within Btrfs' virtual raid-like block addresses.  That is enough, for example, to show which places within a reflinked file are the same or different from a related file; this can be very useful for saving time and bandwidth during backups.
